Repository frappe/helpdesk, pull requests merged in 2023-05, with the labels that each got.

#1141 fix(ui): customer portal: ticket badge color
  desk/src/components/portal/tickets/TicketList.vue
Labels: design, bug-fix

#1143 fix(ux): customer portal: disallow empty messages
  desk/src/pages/portal/ticketing/Ticket.vue
  desk/src/utils/editor.ts
Labels: bug-fix

#1147 fix(ux): use template only if raised via customer portal
  helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Labels: bug-fix

#1149 feat: brand logo for auth pages
  desk/src/App.vue
  desk/src/components/global/LoginBox.vue
  desk/src/router.js
  desk/src/stores/config.ts
  helpdesk/api/config.py
  helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
Labels: enhancement

#1157 Modify replied email subject:
  helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Labels: enhancement

#1159 fix(ui): sla: time capsule width
  desk/src/pages/desk/settings/sla/SlaPolicy.vue
Labels: bug-fix

#1167 feat(ux): config: brand favicon
  desk/src/stores/config.ts
  helpdesk/api/config.py
Labels: enhancement

#1171 feat(ui): badge for new ticket
  desk/src/components/desk/tickets/TicketSummary.vue
  desk/src/pages/desk/ticket/TicketSingle.vue
  desk/src/pages/desk/ticket/data.ts
Labels: enhancement

#1172 fix(ui): list items alignment (to top)
  desk/src/components/desk/tickets/TicketSummary.vue
  desk/src/pages/desk/Tickets.vue
Labels: bug-fix

#1158 refactor: dashboard
  desk/src/components/charts/LineChart.vue
  desk/src/components/charts/PieChart.vue
  desk/src/components/charts/SingleString.vue
  desk/src/components/charts/theme.ts
  desk/src/components/desk/dashboard/CustomerSatisfactionChart.vue
  desk/src/components/desk/dashboard/SlaSummaryCards.vue
  desk/src/components/desk/dashboard/TicketStatusCards.vue
  desk/src/components/desk/dashboard/TicketSummaryChart.vue
  desk/src/components/desk/dashboard/TicketTrendsChart.vue
  desk/src/components/desk/dashboard/TicketTypeChart.vue
  desk/src/components/desk/dashboard/theme.js
  desk/src/components/desk/sidebar/SideBar.vue
  desk/src/pages/desk/Dashboard.vue
  desk/src/pages/desk/DeskDashboard.vue
  desk/src/router.js
  desk/src/stores/auth.ts
  helpdesk/api/auth.py
  helpdesk/api/dashboard.py
Labels: enhancement

#1188 fix(backend): wrong doctype: `SLA` -> `HD Service Level Agreement`
  helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Labels: bug-fix

#1190 fix(ui): missing custom fields
  desk/src/pages/desk/ticket/CustomFieldList.vue
Labels: bug-fix

#1191 fix(api): `get_list`: remove limit
  helpdesk/extends/client.py
Labels: bug-fix

#1192 fix(ui): hide custom fields without value
  desk/src/pages/desk/ticket/CustomFieldList.vue
Labels: bug-fix

#1193 fix(ux): on agent response: auto mark as 'Replied'
  helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
  helpdesk/utils.py
Labels: bug-fix

#1194 fix(ux): can not respond to new ticket
  helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Labels: bug-fix

#1195 fix(ux): stores: set a high number as `pageLimit`
  desk/src/stores/agent.ts
  desk/src/stores/contact.ts
  desk/src/stores/team.ts
  desk/src/stores/ticketPriority.ts
  desk/src/stores/ticketType.ts
Labels: bug-fix

#1198 fix(ux): ticket page: can not back go back if no history
  desk/src/pages/desk/ticket/TopBar.vue
Labels: bug-fix

#1201 fix(ux): keymaps: override only if a combo is active
  desk/src/stores/keymap.ts
Labels: bug-fix

#1204 fix(ux): ticket details: show save button only if there is a change
  desk/src/pages/desk/ticket/TicketDetails.vue
Labels: enhancement

#1197 feat: onboarding
  desk/src/assets/images/yandex.png
  desk/src/pages/desk/AgentRoot.vue
  desk/src/pages/onboarding/OnboardingIntro.vue
  desk/src/pages/onboarding/SetupFavicon.vue
  desk/src/pages/onboarding/SetupLogo.vue
  desk/src/pages/onboarding/SetupName.vue
  desk/src/pages/onboarding/SetupSkipEmail.vue
  desk/src/pages/onboarding/SimpleOnboarding.vue
  desk/src/pages/onboarding/SuccessMessage.vue
  desk/src/pages/onboarding/email/EmailCredentials.vue
  desk/src/pages/onboarding/email/EmailIntro.vue
  desk/src/pages/onboarding/email/SelectService.vue
  desk/src/pages/onboarding/email/SetupEmail.vue
  desk/src/pages/onboarding/email/SuccessMessage.vue
  desk/src/pages/onboarding/email/data.ts
  desk/src/router.js
  desk/src/stores/config.ts
  helpdesk/api/config.py
  helpdesk/api/settings.py
Labels: enhancement

#1235 fix(ux): sanitize: allow `img`
  desk/src/pages/desk/ticket/CommunicationItem.vue
Labels: bug-fix

#1237 fix(api): dashboard: query
  helpdesk/api/dashboard.py
Labels: bug-fix
